
peserta_gcs_path: "gs://data-sample-bpjs/raw/dm_2021_kepesertaan.csv"
fktp_gcs_path: "gs://data-sample-bpjs/raw/dm_fktp_kapitasi.csv"
fkrtl_gcs_path: "gs://data-sample-bpjs/raw/dm_fkrtl.csv"
fktp_stata_gcs_path: "gs://data-sample-bpjs/stata/DM2021_fktpkapitasi.dta"

data:
    label_column: 'readmitted_30d'
    raw_data_folder: "./data/raw"
    raw_peserta_path: "./data/raw/peserta.csv"
    raw_fktp_path: "./data/raw/fktp.csv"
    raw_fktp_decoded_path: "./data/raw/fktp_decoded.csv"
    raw_fkrtl_path: "./data/raw/fkrtl.csv"
    cleaned_data_folder: "./data/cleaned"
    cleaned_peserta_path: "./data/cleaned/peserta.csv"
    cleaned_fktp_encoded_path: "./data/cleaned/fktp_encoded.csv"
    cleaned_fktp_decoded_path: "./data/cleaned/fktp_decoded.csv"
    cleaned_fkrtl_path: "./data/cleaned/fkrtl.csv"

data_cleaning:
    new_column_names_peserta:
        - no_peserta
        - no_keluarga
        - tanggal_lahir
        - hubungan_keluarga
        - gender
        - status_perkawinan
        - kelas_rawat
        - segmen_peserta
        - provinsi_tempat_tinggal
        - kab_kota_tempat_tinggal
        - kepemilikan_faskes
        - jenis_faskes
        - provinsi_faskes
        - kab_kota_faskes
        - bobot
        - tahun_sampel
        - status_peserta
        - tahun_meninggal
    new_column_names_fktp:
        - no_peserta
        - no_keluarga
        - bobot
        - id_kunjungan_fktp
        - tanggal_datang
        - tanggal_pulang
        - provinsi_fktp
        - kab_kota_fktp
        - kepemilikan_fktp
        - jenis_fktp
        - tipe_fktp
        - tingkat_pelayanan
        - poli_fktp
        - segmen_peserta
        - status_pulang_peserta
        - kode_nama_diagnosis_ICD10
        - kode_diagnosis_ICD10
        - kode_diagnosis
        - nama_diagnosis
        - provinsi_fkrtl
        - kab_kota_fkrtl
        - kepemilikan_fkrtl
        - jenis_fkrtl
        - tipe_fkrtl
        - poli_fkrtl
        - jenis_kunjungan_fktp
    new_column_names_fkrtl:
        - no_peserta
        - no_keluarga
        - bobot
        - id_kunjungan_fktp
        - id_kunjungan_fkrtl
        - tanggal_datang
        - tanggal_pulang
        - provinsi_fkrtl
        - kab_kota_fkrtl
        - kepemilikan_fkrtl
        - jenis_fkrtl
        - tipe_fkrtl
        - tingkat_pelayanan
        - poli_fkrtl
        - segmen_peserta
        - kelas_iuran_premi
        - status_pulang_peserta
        - kode_nama_diagnosis_ICD10
        - kode_diagnosis_ICD10
        - kode_diagnosis
        - nama_diagnosis
        - kode_nama_diagnosis_primer_ICD10
        - kode_diagnosis_primer_ICD10
        - kode_diagnosis_primer
        - nama_diagnosis_primer
        - kode_INACBGs
        - deskripsi_INACBGs
        - kode_casemix
        - kelompok_kasus
        - spesifikasi_kelompok_kasus
        - tingkat_keparahan_kelompok_kasus
        - provinsi_perujuk
        - kab_kota_perujuk
        - kepemilikan_perujuk
        - jenis_perujuk
        - tipe_perujuk
        - jenis_prosedur
        - tarif_regional_INACBGs
        - group_tarif_INACBGs
        - kode_sub_acute
        - tarif_sub_acute
        - kode_procedures
        - deskripsi_procedures
        - tarif_procedures
        - kode_prosthesis
        - deskripsi_prosthesis
        - tarif_prosthesis
        - kode_investigation
        - deskripsi_investigation
        - tarif_investigation
        - kode_drugs
        - deskripsi_drugs
        - tarif_drugs
        - biaya_tagih
        - biaya_verifikasi